import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/context/AuthContext";
import Protected from "@/components/Protected";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body className={inter.className}>
          <main className="flex ">
            <section className="w-[18%]">
              <Navbar />
            </section>

            <section
              className={`
                 w-[82%] bg-[#fbfbfb] h-screen`}
            >
              {" "}
              <Protected>{children}</Protected>
            </section>
          </main>
        </body>
      </AuthContextProvider>
    </html>
  );
}
